"""add_stock_type_and_dividend_fields

Revision ID: 7f785400ecea
Revises: 
Create Date: 2026-02-03 22:16:47.944928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f785400ecea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create enum type if it doesn't exist
    op.execute("DO $$ BEGIN CREATE TYPE stocktype AS ENUM ('GROWTH', 'DIVIDEND', 'HYBRID'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Add missing columns
    op.add_column('fundamentals', sa.Column('dividend_yield', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('dividend_per_share', sa.Float(), nullable=True))
    op.add_column('fundamentals', sa.Column('dividend_payout_ratio', sa.Float(), nullable=True))
    
    # Add stock_type column to stocks table
    op.add_column('stocks', sa.Column('stock_type', sa.Enum('GROWTH', 'DIVIDEND', 'HYBRID', name='stocktype'), nullable=True))
    op.create_index(op.f('ix_stocks_stock_type'), 'stocks', ['stock_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_stock_type'), table_name='stocks')
    op.drop_column('stocks', 'stock_type')
    op.drop_column('fundamentals', 'dividend_payout_ratio')
    op.drop_column('fundamentals', 'dividend_per_share')
    op.drop_column('fundamentals', 'dividend_yield')
    op.execute("DROP TYPE IF EXISTS stocktype")
    # ### end Alembic commands ###
