"""add_asset_type_for_etfs_and_mutual_funds

Revision ID: b756e412181b
Revises: 7f785400ecea
Create Date: 2026-02-03 23:19:45.944253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b756e412181b'
down_revision = '7f785400ecea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_fundamentals_stock'), table_name='fundamentals')
    op.create_index(op.f('ix_fundamentals_id'), 'fundamentals', ['id'], unique=False)
    op.create_index(op.f('ix_fundamentals_stock_id'), 'fundamentals', ['stock_id'], unique=False)
    op.alter_column('signal_history', 'signal_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BUY', 'HOLD', 'SELL', 'NO_SIGNAL', name='signaltype'),
               existing_nullable=False)
    op.drop_index(op.f('idx_signal_history_created'), table_name='signal_history')
    op.drop_index(op.f('idx_signal_history_stock'), table_name='signal_history')
    op.drop_index(op.f('idx_signal_history_type'), table_name='signal_history')
    op.create_index(op.f('ix_signal_history_created_at'), 'signal_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_signal_history_id'), 'signal_history', ['id'], unique=False)
    op.create_index(op.f('ix_signal_history_signal_type'), 'signal_history', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signal_history_stock_id'), 'signal_history', ['stock_id'], unique=False)
    op.alter_column('signals', 'signal_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BUY', 'HOLD', 'SELL', 'NO_SIGNAL', name='signaltype'),
               existing_nullable=False)
    op.alter_column('signals', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'),
               existing_nullable=False)
    op.alter_column('signals', 'holding_period',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SHORT', 'MEDIUM', 'LONG', name='holdingperiod'),
               existing_nullable=False)
    op.alter_column('signals', 'explanation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('idx_signals_created'), table_name='signals')
    op.drop_index(op.f('idx_signals_stock'), table_name='signals')
    op.drop_index(op.f('idx_signals_type'), table_name='signals')
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_stock_id'), 'signals', ['stock_id'], unique=False)
    op.add_column('stocks', sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'MUTUAL_FUND', name='assettype'), nullable=True))
    op.alter_column('stocks', 'market',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('US', 'NGX', name='market'),
               existing_nullable=False)
    op.drop_index(op.f('idx_stocks_active'), table_name='stocks')
    op.drop_index(op.f('idx_stocks_market'), table_name='stocks')
    op.drop_index(op.f('idx_stocks_symbol'), table_name='stocks')
    op.drop_constraint(op.f('stocks_symbol_key'), 'stocks', type_='unique')
    op.create_index(op.f('ix_stocks_asset_type'), 'stocks', ['asset_type'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_is_active'), 'stocks', ['is_active'], unique=False)
    op.create_index(op.f('ix_stocks_market'), 'stocks', ['market'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.drop_index(op.f('idx_technical_indicators_stock'), table_name='technical_indicators')
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_stock_id'), 'technical_indicators', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_indicators_stock_id'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.create_index(op.f('idx_technical_indicators_stock'), 'technical_indicators', ['stock_id'], unique=False)
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_market'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_is_active'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_asset_type'), table_name='stocks')
    op.create_unique_constraint(op.f('stocks_symbol_key'), 'stocks', ['symbol'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.create_index(op.f('idx_stocks_market'), 'stocks', ['market'], unique=False)
    op.create_index(op.f('idx_stocks_active'), 'stocks', ['is_active'], unique=False)
    op.alter_column('stocks', 'market',
               existing_type=sa.Enum('US', 'NGX', name='market'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('stocks', 'asset_type')
    op.drop_index(op.f('ix_signals_stock_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.create_index(op.f('idx_signals_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('idx_signals_stock'), 'signals', ['stock_id'], unique=False)
    op.create_index(op.f('idx_signals_created'), 'signals', ['created_at'], unique=False)
    op.alter_column('signals', 'explanation',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('signals', 'holding_period',
               existing_type=sa.Enum('SHORT', 'MEDIUM', 'LONG', name='holdingperiod'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('signals', 'risk_level',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('signals', 'signal_type',
               existing_type=sa.Enum('BUY', 'HOLD', 'SELL', 'NO_SIGNAL', name='signaltype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_signal_history_stock_id'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_signal_type'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_id'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_created_at'), table_name='signal_history')
    op.create_index(op.f('idx_signal_history_type'), 'signal_history', ['signal_type'], unique=False)
    op.create_index(op.f('idx_signal_history_stock'), 'signal_history', ['stock_id'], unique=False)
    op.create_index(op.f('idx_signal_history_created'), 'signal_history', ['created_at'], unique=False)
    op.alter_column('signal_history', 'signal_type',
               existing_type=sa.Enum('BUY', 'HOLD', 'SELL', 'NO_SIGNAL', name='signaltype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_fundamentals_stock_id'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_id'), table_name='fundamentals')
    op.create_index(op.f('idx_fundamentals_stock'), 'fundamentals', ['stock_id'], unique=False)
    # ### end Alembic commands ###
